import type { NewsItem } from "@/types/news";

export const mockNews: NewsItem[] = [
  {
    id: 1,
    title: "Show HN: I built an open-source AI code reviewer that catches bugs before PRs",
    points: 1847,
    author: "sylw99",
    published: "2026-06-02 08:30 UTC",
    url: "https://example.com/ai-code-reviewer",
    text: null,
    comments: 342,
  },
  {
    id: 2,
    title: "The Rise and Fall of the $600M Verkada Hack",
    points: 1256,
    author: "todsacerdoti",
    published: "2026-06-02 07:15 UTC",
    url: "https://example.com/verkada-hack",
    text: null,
    comments: 289,
  },
  {
    id: 3,
    title: "Ask HN: What are you working on? (June 2026)",
    points: 1123,
    author: "dang",
    published: "2026-06-02 06:00 UTC",
    url: null,
    text: "It's that time again! Share what you've been building, tinkering with, or thinking about this month.",
    comments: 876,
  },
  {
    id: 4,
    title: "But what is a GPT? Transformers visualized",
    points: 987,
    author: "3blue1brown",
    published: "2026-06-01 22:45 UTC",
    url: "https://example.com/transformers-viz",
    text: null,
    comments: 215,
  },
  {
    id: 5,
    title: "SQLite in the Browser: A Technical Deep Dive",
    points: 876,
    author: "lovasoa",
    published: "2026-06-01 20:30 UTC",
    url: "https://example.com/sqlite-browser",
    text: null,
    comments: 178,
  },
  {
    id: 6,
    title: "How we reduced Docker image size by 95%",
    points: 834,
    author: "dockerfan42",
    published: "2026-06-01 19:00 UTC",
    url: "https://example.com/docker-slim",
    text: null,
    comments: 203,
  },
  {
    id: 7,
    title: "Let's build a full-text search engine in Go",
    points: 792,
    author: "philips",
    published: "2026-06-01 17:45 UTC",
    url: "https://example.com/search-engine-go",
    text: null,
    comments: 145,
  },
  {
    id: 8,
    title: "Show HN: DVC 4.0 – data version control with SQL-based queries",
    points: 721,
    author: "dberstein",
    published: "2026-06-01 16:30 UTC",
    url: "https://example.com/dvc-4",
    text: null,
    comments: 167,
  },
  {
    id: 9,
    title: "Rust in the Linux Kernel: One Year Later",
    points: 698,
    author: "arjanmels",
    published: "2026-06-01 15:00 UTC",
    url: "https://example.com/rust-linux-kernel",
    text: null,
    comments: 312,
  },
  {
    id: 10,
    title: "Why we switched from PostgreSQL to DuckDB for analytics",
    points: 654,
    author: "analytics_guy",
    published: "2026-06-01 14:15 UTC",
    url: "https://example.com/pg-to-duckdb",
    text: null,
    comments: 198,
  },
  {
    id: 11,
    title: "My Todo list over engineering",
    points: 621,
    author: "todsacerdoti",
    published: "2026-06-01 13:00 UTC",
    url: "https://example.com/todo-overengineering",
    text: null,
    comments: 234,
  },
  {
    id: 12,
    title: "Show HN: I made a DNS server in 200 lines of Python",
    points: 598,
    author: "pythonista",
    published: "2026-06-01 12:30 UTC",
    url: "https://example.com/dns-python",
    text: null,
    comments: 145,
  },
  {
    id: 13,
    title: "The CSS framework war is over. Here's what won.",
    points: 567,
    author: "frontend_dev",
    published: "2026-06-01 11:45 UTC",
    url: "https://example.com/css-framework-war",
    text: null,
    comments: 423,
  },
  {
    id: 14,
    title: "How Figma builds its real-time collaboration engine",
    points: 543,
    author: "figmateam",
    published: "2026-06-01 10:30 UTC",
    url: "https://example.com/figma-realtime",
    text: null,
    comments: 167,
  },
  {
    id: 15,
    title: "Building a serverless RAG pipeline with Cloudflare Workers",
    points: 512,
    author: "cloudflare_dev",
    published: "2026-06-01 09:00 UTC",
    url: "https://example.com/rag-workers",
    text: null,
    comments: 134,
  },
  {
    id: 16,
    title: "Why does printf work? A deep dive into variadic functions in C",
    points: 498,
    author: "c_expert",
    published: "2026-06-01 08:15 UTC",
    url: "https://example.com/printf-deep-dive",
    text: null,
    comments: 189,
  },
  {
    id: 17,
    title: "PostgreSQL 19: What's new",
    points: 476,
    author: "pg_enthusiast",
    published: "2026-06-01 07:30 UTC",
    url: "https://example.com/pg19-whats-new",
    text: null,
    comments: 156,
  },
  {
    id: 18,
    title: "Ask HN: How do you stay motivated as a solo founder?",
    points: 454,
    author: "solo_founder",
    published: "2026-06-01 06:45 UTC",
    url: null,
    text: "I've been building my product for 18 months with no revenue. How do you keep going?",
    comments: 345,
  },
  {
    id: 19,
    title: "A minimalist guide to Tmux",
    points: 432,
    author: "terminal_wizard",
    published: "2026-06-01 05:30 UTC",
    url: "https://example.com/tmux-minimal",
    text: null,
    comments: 112,
  },
  {
    id: 20,
    title: "Show HN: Open-source alternative to Notion with local-first sync",
    points: 412,
    author: "build_in_public",
    published: "2026-06-01 04:00 UTC",
    url: "https://example.com/notion-alt",
    text: null,
    comments: 267,
  },
  {
    id: 21,
    title: "The hidden complexity of sorting algorithms",
    points: 398,
    author: "algo_expert",
    published: "2026-06-01 03:15 UTC",
    url: "https://example.com/sorting-complexity",
    text: null,
    comments: 145,
  },
  {
    id: 22,
    title: "TypeScript 6.0 announced: exhaustiveness checking by default",
    points: 376,
    author: "ts_team",
    published: "2026-06-01 02:30 UTC",
    url: "https://example.com/ts6-announce",
    text: null,
    comments: 298,
  },
  {
    id: 23,
    title: "How I optimized a Python service to handle 1M requests/second",
    points: 354,
    author: "perf_ninja",
    published: "2026-06-01 01:45 UTC",
    url: "https://example.com/python-1m-rps",
    text: null,
    comments: 234,
  },
  {
    id: 24,
    title: "Why functional programming matters (in 2026)",
    points: 332,
    author: "fp_advocate",
    published: "2026-06-01 00:30 UTC",
    url: "https://example.com/fp-matters-2026",
    text: null,
    comments: 312,
  },
  {
    id: 25,
    title: "Building a WebGL game in 48 hours: a post-mortem",
    points: 312,
    author: "game_jammer",
    published: "2026-05-31 23:00 UTC",
    url: "https://example.com/webgl-48h",
    text: null,
    comments: 98,
  },
  {
    id: 26,
    title: "The state of WebAssembly in 2026",
    points: 298,
    author: "wasm_watcher",
    published: "2026-05-31 22:15 UTC",
    url: "https://example.com/wasm-2026",
    text: null,
    comments: 167,
  },
  {
    id: 27,
    title: "How Uber migrated 200 microservices to Kubernetes",
    points: 276,
    author: "uber_eng",
    published: "2026-05-31 21:00 UTC",
    url: "https://example.com/uber-k8s-migration",
    text: null,
    comments: 189,
  },
  {
    id: 28,
    title: "Show HN: I wrote a book on systems design for senior engineers",
    points: 254,
    author: "systems_author",
    published: "2026-05-31 20:30 UTC",
    url: "https://example.com/systems-design-book",
    text: null,
    comments: 134,
  },
  {
    id: 29,
    title: "The database built for AI agents: Kùzu 2.0",
    points: 234,
    author: "kuzu_team",
    published: "2026-05-31 19:45 UTC",
    url: "https://example.com/kuzu-2",
    text: null,
    comments: 87,
  },
  {
    id: 30,
    title: "You don't need Docker: building reproducible dev environments with Nix",
    points: 212,
    author: "nix_fan",
    published: "2026-05-31 18:30 UTC",
    url: "https://example.com/nix-dev-env",
    text: null,
    comments: 156,
  },
];
